AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
    Auth:
       DefaultAuthorizer: MyLambdaTokenAuthorizer
       Authorizers:
         MyLambdaTokenAuthorizer:
           FunctionArn: !GetAtt LamdbaFunction.Arn
       Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  LamdbaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./    
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        getCounter:
          Type: Api
          Properties:
            Path: /vetor_palavras
            Method: any
            RestApiId: !Ref ApiGatewayApi
            Policies:
            - AmazonDynamoDBFullAccess
            - AWSLambdaBasicExecutionRole
            - AWSLambdaVPCAccessExecutionRole
            - Version: '2012-10-17' # Policy Document
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:*
                  Resource: 'arn:aws:dynamodb:*:*:table/dynamo_db_table_endpoint'
            ListFunctionCors:
              Type: Api
              Properties:
                RestApiId: !Ref ApiGatewayApi
                Path: /list
                Method: OPTIONS
                Auth:
                  Authorizer: null         
  vetor_palavras:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: eventDateTime
          AttributeType: S
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE