AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
    Auth:
     UsagePlan:
      CreateUsagePlan: PER_API
      Description: Usage plan for this API
      Quota:
       Limit: 500
       Period: MONTH
      Throttle:
       BurstLimit: 100
       RateLimit: 50
  LamdbaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src    
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        getCounter:
          Type: Api
          Properties:
            Path: /vetor_palavras
            Method: ANY
            RestApiId: !Ref ApiGatewayApi
            Policies:
            - AmazonDynamoDBFullAccess
            - AWSLambdaBasicExecutionRole
            - AWSLambdaVPCAccessExecutionRole
            - CloudWatchLogsFullAccess 
  vetor_palavras:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: eventDateTime
          AttributeType: S
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE