AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
    Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaRequestAuthorizer:
            FunctionArn: !GetAtt LamdbaFunction.Arn
            FunctionInvokeRole: !GetAtt LamdbaFunction.Arn
            Identity:
              Headers:
                - Authorization
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: true
  LamdbaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./    
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        getCounter:
          Type: Api
          Properties:
            Path: /vetor_palavras
            Method: ANY
            RestApiId: !Ref ApiGatewayApi
            Policies:
            - AmazonDynamoDBFullAccess
            - AWSLambdaBasicExecutionRole
            - AWSLambdaVPCAccessExecutionRole
            - CloudWatchLogsFullAccess 
  vetor_palavras:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: eventDateTime
          AttributeType: S
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE